# Generated by Django 4.2.19 on 2025-03-27 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sproutly', '0003_autoschedule_nutrients_control_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebscrapedPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.URLField()),
                ('info_url', models.URLField()),
                ('scientific_name', models.CharField(blank=True, max_length=100, null=True)),
                ('light_description', models.CharField(blank=True, max_length=100, null=True)),
                ('light_t0', models.IntegerField(blank=True, null=True)),
                ('light_duration', models.IntegerField(blank=True, null=True)),
                ('water_description', models.CharField(blank=True, max_length=100, null=True)),
                ('temp_min', models.IntegerField(blank=True, null=True)),
                ('temp_max', models.IntegerField(blank=True, null=True)),
                ('humidity_min', models.IntegerField(blank=True, null=True)),
                ('humidity_max', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to='sproutly.plant')),
            ],
        ),
    ]
