# Generated by Django 4.2.19 on 2025-03-28 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sproutly', '0005_sensordata_humidity_sensordata_temperature_c_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to='sproutly.plant'),
        ),
    ]
