# Generated by Django 4.2.19 on 2025-03-28 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sproutly', '0006_alter_sensordata_plant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='image',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='plant',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='health_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
