# Generated by Django 4.2.19 on 2025-03-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sproutly', '0007_remove_plant_created_at_remove_plant_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
