# Generated by Django 4.2.19 on 2025-04-07 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sproutly', '0008_alter_plant_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoschedule',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='autoschedule',
            name='humidity_control_enabled',
        ),
        migrations.RemoveField(
            model_name='autoschedule',
            name='humidity_target',
        ),
        migrations.RemoveField(
            model_name='autoschedule',
            name='lighting_enabled',
        ),
        migrations.RemoveField(
            model_name='autoschedule',
            name='lighting_hours',
        ),
        migrations.RemoveField(
            model_name='autoschedule',
            name='nutrients_control_enabled',
        ),
        migrations.RemoveField(
            model_name='autoschedule',
            name='nutrients_target',
        ),
        migrations.RemoveField(
            model_name='autoschedule',
            name='temperature_control_enabled',
        ),
        migrations.RemoveField(
            model_name='autoschedule',
            name='temperature_target',
        ),
        migrations.RemoveField(
            model_name='autoschedule',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='autoschedule',
            name='watering_amount',
        ),
        migrations.RemoveField(
            model_name='autoschedule',
            name='watering_enabled',
        ),
        migrations.AddField(
            model_name='autoschedule',
            name='light_frequency',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autoschedule',
            name='light_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autoschedule',
            name='max_humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autoschedule',
            name='max_temp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autoschedule',
            name='min_humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autoschedule',
            name='min_temp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autoschedule',
            name='water_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autoschedule',
            name='water_frequency',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
