# Generated by Django 4.2.19 on 2025-04-07 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sproutly', '0009_remove_autoschedule_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
