# Generated by Django 4.2.19 on 2025-04-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sproutly', '0010_alter_plant_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoschedule',
            name='light_frequency',
        ),
        migrations.AddField(
            model_name='autoschedule',
            name='light_intensity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='conductivity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='lux',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='nitrogen',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='ph',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='phosphorus',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='potassium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='soil_moisture',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='soil_temp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webscrapedplant',
            name='ph_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webscrapedplant',
            name='ph_min',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
